"""rename department

Revision ID: 174a8a0b6dc5
Revises: fd78701c864c
Create Date: 2024-10-10 00:43:35.226811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174a8a0b6dc5'
down_revision = 'fd78701c864c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
